server:
  port: 7901
spring:
  application:
    name: provider-user
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO