server:
  port: 8010
spring:
  application:
    name: consumer-client
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO